project:
  type: website
  resources:
    - CNAME

website:
  title: "Pluszone Education"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "English"
        href: english.qmd

format:
  html:
    lang: ko
